version: '3'
 
services:
    apache_img_1:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con_1
        
        build: 
          context: apache
          dockerfile: Dockerfile
        expose:
            - ${APACHE_EXPOSED_PORT}
        environment:
            - APACHE_IP=${APACHE_1_IP}
        volumes:
            - type: volume
              source: web
              target: /src
            - type: bind
              source: ./apache/src
              target: /var/www/html
        networks:
            public_net:
                ipv4_address: ${APACHE_1_IP}
    apache_img_2:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con_2
        build: 
          context: apache
          dockerfile: Dockerfile
        expose:
            - ${APACHE_EXPOSED_PORT}
        environment:
            - APACHE_IP=${APACHE_2_IP}
        volumes:
            - type: volume
              source: web
              target: /src
            - type: bind
              source: ./apache/src
              target: /var/www/html
        networks:
            public_net:
                ipv4_address: ${APACHE_2_IP}

    apache_img_3:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con_3

        build:
          context: apache
          dockerfile: Dockerfile
        expose:
            - ${APACHE_EXPOSED_PORT}
        environment:
            - APACHE_IP=${APACHE_3_IP}
        volumes:
            - type: volume
              source: web
              target: /src
            - type: bind
              source: ./apache/src
              target: /var/www/html
        networks:
            public_net:
                ipv4_address: ${APACHE_3_IP}
    apache_img_4:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con_4

        build:
          context: apache
          dockerfile: Dockerfile
        expose:
            - ${APACHE_EXPOSED_PORT}
        environment:
            - APACHE_IP=${APACHE_4_IP}
        volumes:
            - type: volume
              source: web
              target: /src
            - type: bind
              source: ./apache/src
              target: /var/www/html
        networks:
            public_net:
                ipv4_address: ${APACHE_4_IP}

    haproxy_img:
        build: 
          context: haproxy/
          dockerfile: Dockerfile
        ports:
            - 80:80
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: ${HA_PROXY_IP}
        environment:
            - APACHE_1_IP=${APACHE_1_IP}
            - APACHE_2_IP=${APACHE_2_IP}
            - APACHE_3_IP=${APACHE_3_IP}
            - APACHE_4_IP=${APACHE_4_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}

volumes:
  web:
